# permissions for end users to view vectorpipelines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vectorpipeline-viewer-role
rules:
- apiGroups:
  - observability.kaasops.io
  resources:
  - vectorpipelines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - observability.kaasops.io
  resources:
  - vectorpipelines/status
  verbs:
  - get
