image:
  repository: kaasops/vector-operator
  tag: "latest"
  pullPolicy: IfNotPresent
  
  securityContext: 
    allowPrivilegeEscalation: false
    runAsGroup: 1000
    runAsNonRoot: true    
    readOnlyRootFilesystem: true
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop:
        - ALL

resources: 
  limits:
    cpu: "2"
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 50Mi

rbac:
 create: true

serviceAccount:
  create: false
  name: "vector-operator"
  annotations: {}

ClusterVectorPipeline:
    name: test1
    spec: {}  

VectorPipeline: 
  name: test12
  spec: {}    
